Update community page
pixie-io/px.dev pull request #28
Opened 2021-07-29 04:13 UTC by aimichelle

2021-07-29 07:31 UTC, htroisi approved these changes

2021-08-26 20:36 UTC, htroisi submitted a review, later dismissed

2021-09-20 21:26 UTC, vihangm approved these changes

2021-09-20 21:32 UTC, vihangm requested changes

2021-09-20 21:32 UTC, vihangm commented on src/pages/community.js
> +      date: 'September 23, 2021',
I think this one is cancelled

2021-09-20 21:32 UTC, vihangm commented on src/pages/community.js
>        location: 'Online (Zoom)',
I think this one is "in person" at kubecon

2021-09-20 22:42 UTC, vihangm approved these changes

2021-09-20 22:43 UTC, merged